---
# Make sure galaxy module Juniper.junos is installed for this to work
- name: Install Junos OS
  hosts: dc1
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no
  vars:
    wait_time: 3600
    pkg_dir: /var/tmp/junos-install # Can be a variable for better portability
    OS_version: 14.1R1.10 # Can be a variable for better portability
    OS_package: jinstall-14.1R1.10-domestic-signed.tgz # Can be a variable for better portability
    log_dir: /var/log/ansible # Can be a variable for better portability

  tasks:
    - name: Checking NETCONF connectivity
      wait_for: host={{ inventory_hostname }} port=830 timeout=5
    - name: Install Junos OS package
      juniper_junos_software:
        reboot: yes
        version: "{{ OS_version }}"
        package: "{{ pkg_dir }}/{{ OS_package }}"
        logfile: "{{ log_dir }}/software.log"
      register: sw
      notify:
        - wait_reboot

  handlers:
    - name: wait_reboot
      wait_for: host={{ inventory_hostname }} port=830 timeout={{ wait_time }}
      when: not sw.check_mode
